//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("xvdenovembro1565Model", "FK_cangooru_Location_cangooru_Region", "cangooru_Region", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Cangooru.Repositories.cangooru_Region), "cangooru_Location", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cangooru.Repositories.cangooru_Location), true)]
[assembly: EdmRelationshipAttribute("xvdenovembro1565Model", "FK_cangooru_Location_Order_cangooru_Location", "cangooru_Location", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cangooru.Repositories.cangooru_Location), "cangooru_Location_Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cangooru.Repositories.cangooru_Location_Order), true)]
[assembly: EdmRelationshipAttribute("xvdenovembro1565Model", "FK_cangooru_OrderAddressInformation_OrderAddressInformationType", "cangooru_LocationType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cangooru.Repositories.cangooru_LocationType), "cangooru_Location", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cangooru.Repositories.cangooru_Location), true)]
[assembly: EdmRelationshipAttribute("xvdenovembro1565Model", "FK_cangooru_Location_Order_cangooru_Order", "cangooru_Order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cangooru.Repositories.cangooru_Order), "cangooru_Location_Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cangooru.Repositories.cangooru_Location_Order), true)]
[assembly: EdmRelationshipAttribute("xvdenovembro1565Model", "FK_cangooru_Order_cangooru_OrderStatus", "cangooru_OrderStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Cangooru.Repositories.cangooru_OrderStatus), "cangooru_Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cangooru.Repositories.cangooru_Order), true)]
[assembly: EdmRelationshipAttribute("xvdenovembro1565Model", "FK_cangooru_Purchase_cangooru_Order", "cangooru_Order", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Cangooru.Repositories.cangooru_Order), "cangooru_Purchase", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cangooru.Repositories.cangooru_Purchase), true)]
[assembly: EdmRelationshipAttribute("xvdenovembro1565Model", "FK_cangooru_Purchase_cangooru_PurchaseStatus", "cangooru_PurchaseStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cangooru.Repositories.cangooru_PurchaseStatus), "cangooru_Purchase", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cangooru.Repositories.cangooru_Purchase), true)]

#endregion

namespace Cangooru.Repositories
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CangooruEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CangooruEntities object using the connection string found in the 'CangooruEntities' section of the application configuration file.
        /// </summary>
        public CangooruEntities() : base("name=CangooruEntities", "CangooruEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CangooruEntities object.
        /// </summary>
        public CangooruEntities(string connectionString) : base(connectionString, "CangooruEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CangooruEntities object.
        /// </summary>
        public CangooruEntities(EntityConnection connection) : base(connection, "CangooruEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cangooru_Company> cangooru_Company
        {
            get
            {
                if ((_cangooru_Company == null))
                {
                    _cangooru_Company = base.CreateObjectSet<cangooru_Company>("cangooru_Company");
                }
                return _cangooru_Company;
            }
        }
        private ObjectSet<cangooru_Company> _cangooru_Company;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cangooru_Location> cangooru_Location
        {
            get
            {
                if ((_cangooru_Location == null))
                {
                    _cangooru_Location = base.CreateObjectSet<cangooru_Location>("cangooru_Location");
                }
                return _cangooru_Location;
            }
        }
        private ObjectSet<cangooru_Location> _cangooru_Location;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cangooru_Location_Order> cangooru_Location_Order
        {
            get
            {
                if ((_cangooru_Location_Order == null))
                {
                    _cangooru_Location_Order = base.CreateObjectSet<cangooru_Location_Order>("cangooru_Location_Order");
                }
                return _cangooru_Location_Order;
            }
        }
        private ObjectSet<cangooru_Location_Order> _cangooru_Location_Order;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cangooru_LocationType> cangooru_LocationType
        {
            get
            {
                if ((_cangooru_LocationType == null))
                {
                    _cangooru_LocationType = base.CreateObjectSet<cangooru_LocationType>("cangooru_LocationType");
                }
                return _cangooru_LocationType;
            }
        }
        private ObjectSet<cangooru_LocationType> _cangooru_LocationType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cangooru_Order> cangooru_Order
        {
            get
            {
                if ((_cangooru_Order == null))
                {
                    _cangooru_Order = base.CreateObjectSet<cangooru_Order>("cangooru_Order");
                }
                return _cangooru_Order;
            }
        }
        private ObjectSet<cangooru_Order> _cangooru_Order;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cangooru_OrderStatus> cangooru_OrderStatus
        {
            get
            {
                if ((_cangooru_OrderStatus == null))
                {
                    _cangooru_OrderStatus = base.CreateObjectSet<cangooru_OrderStatus>("cangooru_OrderStatus");
                }
                return _cangooru_OrderStatus;
            }
        }
        private ObjectSet<cangooru_OrderStatus> _cangooru_OrderStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cangooru_Purchase> cangooru_Purchase
        {
            get
            {
                if ((_cangooru_Purchase == null))
                {
                    _cangooru_Purchase = base.CreateObjectSet<cangooru_Purchase>("cangooru_Purchase");
                }
                return _cangooru_Purchase;
            }
        }
        private ObjectSet<cangooru_Purchase> _cangooru_Purchase;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cangooru_PurchaseStatus> cangooru_PurchaseStatus
        {
            get
            {
                if ((_cangooru_PurchaseStatus == null))
                {
                    _cangooru_PurchaseStatus = base.CreateObjectSet<cangooru_PurchaseStatus>("cangooru_PurchaseStatus");
                }
                return _cangooru_PurchaseStatus;
            }
        }
        private ObjectSet<cangooru_PurchaseStatus> _cangooru_PurchaseStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cangooru_Region> cangooru_Region
        {
            get
            {
                if ((_cangooru_Region == null))
                {
                    _cangooru_Region = base.CreateObjectSet<cangooru_Region>("cangooru_Region");
                }
                return _cangooru_Region;
            }
        }
        private ObjectSet<cangooru_Region> _cangooru_Region;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cangooru_Company EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocangooru_Company(cangooru_Company cangooru_Company)
        {
            base.AddObject("cangooru_Company", cangooru_Company);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cangooru_Location EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocangooru_Location(cangooru_Location cangooru_Location)
        {
            base.AddObject("cangooru_Location", cangooru_Location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cangooru_Location_Order EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocangooru_Location_Order(cangooru_Location_Order cangooru_Location_Order)
        {
            base.AddObject("cangooru_Location_Order", cangooru_Location_Order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cangooru_LocationType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocangooru_LocationType(cangooru_LocationType cangooru_LocationType)
        {
            base.AddObject("cangooru_LocationType", cangooru_LocationType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cangooru_Order EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocangooru_Order(cangooru_Order cangooru_Order)
        {
            base.AddObject("cangooru_Order", cangooru_Order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cangooru_OrderStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocangooru_OrderStatus(cangooru_OrderStatus cangooru_OrderStatus)
        {
            base.AddObject("cangooru_OrderStatus", cangooru_OrderStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cangooru_Purchase EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocangooru_Purchase(cangooru_Purchase cangooru_Purchase)
        {
            base.AddObject("cangooru_Purchase", cangooru_Purchase);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cangooru_PurchaseStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocangooru_PurchaseStatus(cangooru_PurchaseStatus cangooru_PurchaseStatus)
        {
            base.AddObject("cangooru_PurchaseStatus", cangooru_PurchaseStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cangooru_Region EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocangooru_Region(cangooru_Region cangooru_Region)
        {
            base.AddObject("cangooru_Region", cangooru_Region);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xvdenovembro1565Model", Name="cangooru_Company")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cangooru_Company : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cangooru_Company object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static cangooru_Company Createcangooru_Company(global::System.Guid id)
        {
            cangooru_Company cangooru_Company = new cangooru_Company();
            cangooru_Company.Id = id;
            return cangooru_Company;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CNPJ
        {
            get
            {
                return _CNPJ;
            }
            set
            {
                OnCNPJChanging(value);
                ReportPropertyChanging("CNPJ");
                _CNPJ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CNPJ");
                OnCNPJChanged();
            }
        }
        private global::System.String _CNPJ;
        partial void OnCNPJChanging(global::System.String value);
        partial void OnCNPJChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressExtraInfo
        {
            get
            {
                return _AddressExtraInfo;
            }
            set
            {
                OnAddressExtraInfoChanging(value);
                ReportPropertyChanging("AddressExtraInfo");
                _AddressExtraInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddressExtraInfo");
                OnAddressExtraInfoChanged();
            }
        }
        private global::System.String _AddressExtraInfo;
        partial void OnAddressExtraInfoChanging(global::System.String value);
        partial void OnAddressExtraInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private Nullable<global::System.Int64> _Telephone;
        partial void OnTelephoneChanging(Nullable<global::System.Int64> value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Telephone2
        {
            get
            {
                return _Telephone2;
            }
            set
            {
                OnTelephone2Changing(value);
                ReportPropertyChanging("Telephone2");
                _Telephone2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Telephone2");
                OnTelephone2Changed();
            }
        }
        private Nullable<global::System.Int64> _Telephone2;
        partial void OnTelephone2Changing(Nullable<global::System.Int64> value);
        partial void OnTelephone2Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xvdenovembro1565Model", Name="cangooru_Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cangooru_Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cangooru_Location object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="contactName">Initial value of the ContactName property.</param>
        /// <param name="telephone">Initial value of the Telephone property.</param>
        /// <param name="userAccountId">Initial value of the UserAccountId property.</param>
        /// <param name="locationType">Initial value of the LocationType property.</param>
        public static cangooru_Location Createcangooru_Location(global::System.Guid id, global::System.String address, global::System.String contactName, global::System.Int64 telephone, global::System.Guid userAccountId, global::System.Int32 locationType)
        {
            cangooru_Location cangooru_Location = new cangooru_Location();
            cangooru_Location.Id = id;
            cangooru_Location.Address = address;
            cangooru_Location.ContactName = contactName;
            cangooru_Location.Telephone = telephone;
            cangooru_Location.UserAccountId = userAccountId;
            cangooru_Location.LocationType = locationType;
            return cangooru_Location;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressExtraInfo
        {
            get
            {
                return _AddressExtraInfo;
            }
            set
            {
                OnAddressExtraInfoChanging(value);
                ReportPropertyChanging("AddressExtraInfo");
                _AddressExtraInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddressExtraInfo");
                OnAddressExtraInfoChanged();
            }
        }
        private global::System.String _AddressExtraInfo;
        partial void OnAddressExtraInfoChanging(global::System.String value);
        partial void OnAddressExtraInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.Int64 _Telephone;
        partial void OnTelephoneChanging(global::System.Int64 value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Telephone2
        {
            get
            {
                return _Telephone2;
            }
            set
            {
                OnTelephone2Changing(value);
                ReportPropertyChanging("Telephone2");
                _Telephone2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Telephone2");
                OnTelephone2Changed();
            }
        }
        private Nullable<global::System.Int64> _Telephone2;
        partial void OnTelephone2Changing(Nullable<global::System.Int64> value);
        partial void OnTelephone2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserAccountId
        {
            get
            {
                return _UserAccountId;
            }
            set
            {
                OnUserAccountIdChanging(value);
                ReportPropertyChanging("UserAccountId");
                _UserAccountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserAccountId");
                OnUserAccountIdChanged();
            }
        }
        private global::System.Guid _UserAccountId;
        partial void OnUserAccountIdChanging(global::System.Guid value);
        partial void OnUserAccountIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationType
        {
            get
            {
                return _LocationType;
            }
            set
            {
                OnLocationTypeChanging(value);
                ReportPropertyChanging("LocationType");
                _LocationType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationType");
                OnLocationTypeChanged();
            }
        }
        private global::System.Int32 _LocationType;
        partial void OnLocationTypeChanging(global::System.Int32 value);
        partial void OnLocationTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEP
        {
            get
            {
                return _CEP;
            }
            set
            {
                OnCEPChanging(value);
                ReportPropertyChanging("CEP");
                _CEP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEP");
                OnCEPChanged();
            }
        }
        private global::System.String _CEP;
        partial void OnCEPChanging(global::System.String value);
        partial void OnCEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Neightborhood
        {
            get
            {
                return _Neightborhood;
            }
            set
            {
                OnNeightborhoodChanging(value);
                ReportPropertyChanging("Neightborhood");
                _Neightborhood = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Neightborhood");
                OnNeightborhoodChanged();
            }
        }
        private global::System.String _Neightborhood;
        partial void OnNeightborhoodChanging(global::System.String value);
        partial void OnNeightborhoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> RegionId
        {
            get
            {
                return _RegionId;
            }
            set
            {
                OnRegionIdChanging(value);
                ReportPropertyChanging("RegionId");
                _RegionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegionId");
                OnRegionIdChanged();
            }
        }
        private Nullable<global::System.Guid> _RegionId;
        partial void OnRegionIdChanging(Nullable<global::System.Guid> value);
        partial void OnRegionIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Location_cangooru_Region", "cangooru_Region")]
        public cangooru_Region cangooru_Region
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Region>("xvdenovembro1565Model.FK_cangooru_Location_cangooru_Region", "cangooru_Region").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Region>("xvdenovembro1565Model.FK_cangooru_Location_cangooru_Region", "cangooru_Region").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cangooru_Region> cangooru_RegionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Region>("xvdenovembro1565Model.FK_cangooru_Location_cangooru_Region", "cangooru_Region");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cangooru_Region>("xvdenovembro1565Model.FK_cangooru_Location_cangooru_Region", "cangooru_Region", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Location_Order_cangooru_Location", "cangooru_Location_Order")]
        public EntityCollection<cangooru_Location_Order> cangooru_Location_Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cangooru_Location_Order>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Location", "cangooru_Location_Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cangooru_Location_Order>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Location", "cangooru_Location_Order", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_OrderAddressInformation_OrderAddressInformationType", "cangooru_LocationType")]
        public cangooru_LocationType cangooru_LocationType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_LocationType>("xvdenovembro1565Model.FK_cangooru_OrderAddressInformation_OrderAddressInformationType", "cangooru_LocationType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_LocationType>("xvdenovembro1565Model.FK_cangooru_OrderAddressInformation_OrderAddressInformationType", "cangooru_LocationType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cangooru_LocationType> cangooru_LocationTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_LocationType>("xvdenovembro1565Model.FK_cangooru_OrderAddressInformation_OrderAddressInformationType", "cangooru_LocationType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cangooru_LocationType>("xvdenovembro1565Model.FK_cangooru_OrderAddressInformation_OrderAddressInformationType", "cangooru_LocationType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xvdenovembro1565Model", Name="cangooru_Location_Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cangooru_Location_Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cangooru_Location_Order object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="locationId">Initial value of the LocationId property.</param>
        /// <param name="isStartPoint">Initial value of the IsStartPoint property.</param>
        public static cangooru_Location_Order Createcangooru_Location_Order(global::System.Guid orderId, global::System.Guid locationId, global::System.Boolean isStartPoint)
        {
            cangooru_Location_Order cangooru_Location_Order = new cangooru_Location_Order();
            cangooru_Location_Order.OrderId = orderId;
            cangooru_Location_Order.LocationId = locationId;
            cangooru_Location_Order.IsStartPoint = isStartPoint;
            return cangooru_Location_Order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Guid _OrderId;
        partial void OnOrderIdChanging(global::System.Guid value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid LocationId
        {
            get
            {
                return _LocationId;
            }
            set
            {
                if (_LocationId != value)
                {
                    OnLocationIdChanging(value);
                    ReportPropertyChanging("LocationId");
                    _LocationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocationId");
                    OnLocationIdChanged();
                }
            }
        }
        private global::System.Guid _LocationId;
        partial void OnLocationIdChanging(global::System.Guid value);
        partial void OnLocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsStartPoint
        {
            get
            {
                return _IsStartPoint;
            }
            set
            {
                if (_IsStartPoint != value)
                {
                    OnIsStartPointChanging(value);
                    ReportPropertyChanging("IsStartPoint");
                    _IsStartPoint = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsStartPoint");
                    OnIsStartPointChanged();
                }
            }
        }
        private global::System.Boolean _IsStartPoint;
        partial void OnIsStartPointChanging(global::System.Boolean value);
        partial void OnIsStartPointChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OperationTime
        {
            get
            {
                return _OperationTime;
            }
            set
            {
                OnOperationTimeChanging(value);
                ReportPropertyChanging("OperationTime");
                _OperationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OperationTime");
                OnOperationTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _OperationTime;
        partial void OnOperationTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnOperationTimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Location_Order_cangooru_Location", "cangooru_Location")]
        public cangooru_Location cangooru_Location
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Location>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Location", "cangooru_Location").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Location>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Location", "cangooru_Location").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cangooru_Location> cangooru_LocationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Location>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Location", "cangooru_Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cangooru_Location>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Location", "cangooru_Location", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Location_Order_cangooru_Order", "cangooru_Order")]
        public cangooru_Order cangooru_Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Order", "cangooru_Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Order", "cangooru_Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cangooru_Order> cangooru_OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Order", "cangooru_Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Order", "cangooru_Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xvdenovembro1565Model", Name="cangooru_LocationType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cangooru_LocationType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cangooru_LocationType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static cangooru_LocationType Createcangooru_LocationType(global::System.Int32 id, global::System.String name)
        {
            cangooru_LocationType cangooru_LocationType = new cangooru_LocationType();
            cangooru_LocationType.Id = id;
            cangooru_LocationType.Name = name;
            return cangooru_LocationType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_OrderAddressInformation_OrderAddressInformationType", "cangooru_Location")]
        public EntityCollection<cangooru_Location> cangooru_Location
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cangooru_Location>("xvdenovembro1565Model.FK_cangooru_OrderAddressInformation_OrderAddressInformationType", "cangooru_Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cangooru_Location>("xvdenovembro1565Model.FK_cangooru_OrderAddressInformation_OrderAddressInformationType", "cangooru_Location", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xvdenovembro1565Model", Name="cangooru_Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cangooru_Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cangooru_Order object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="protocol">Initial value of the Protocol property.</param>
        public static cangooru_Order Createcangooru_Order(global::System.Guid id, global::System.Int32 protocol)
        {
            cangooru_Order cangooru_Order = new cangooru_Order();
            cangooru_Order.Id = id;
            cangooru_Order.Protocol = protocol;
            return cangooru_Order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderStatusId
        {
            get
            {
                return _OrderStatusId;
            }
            set
            {
                OnOrderStatusIdChanging(value);
                ReportPropertyChanging("OrderStatusId");
                _OrderStatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderStatusId");
                OnOrderStatusIdChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderStatusId;
        partial void OnOrderStatusIdChanging(Nullable<global::System.Int32> value);
        partial void OnOrderStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Protocol
        {
            get
            {
                return _Protocol;
            }
            set
            {
                OnProtocolChanging(value);
                ReportPropertyChanging("Protocol");
                _Protocol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Protocol");
                OnProtocolChanged();
            }
        }
        private global::System.Int32 _Protocol;
        partial void OnProtocolChanging(global::System.Int32 value);
        partial void OnProtocolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> OwnerId
        {
            get
            {
                return _OwnerId;
            }
            set
            {
                OnOwnerIdChanging(value);
                ReportPropertyChanging("OwnerId");
                _OwnerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerId");
                OnOwnerIdChanged();
            }
        }
        private Nullable<global::System.Guid> _OwnerId;
        partial void OnOwnerIdChanging(Nullable<global::System.Guid> value);
        partial void OnOwnerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sender
        {
            get
            {
                return _Sender;
            }
            set
            {
                OnSenderChanging(value);
                ReportPropertyChanging("Sender");
                _Sender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sender");
                OnSenderChanged();
            }
        }
        private global::System.String _Sender;
        partial void OnSenderChanging(global::System.String value);
        partial void OnSenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Receiver
        {
            get
            {
                return _Receiver;
            }
            set
            {
                OnReceiverChanging(value);
                ReportPropertyChanging("Receiver");
                _Receiver = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Receiver");
                OnReceiverChanged();
            }
        }
        private global::System.String _Receiver;
        partial void OnReceiverChanging(global::System.String value);
        partial void OnReceiverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> DeliveryUserId
        {
            get
            {
                return _DeliveryUserId;
            }
            set
            {
                OnDeliveryUserIdChanging(value);
                ReportPropertyChanging("DeliveryUserId");
                _DeliveryUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryUserId");
                OnDeliveryUserIdChanged();
            }
        }
        private Nullable<global::System.Guid> _DeliveryUserId;
        partial void OnDeliveryUserIdChanging(Nullable<global::System.Guid> value);
        partial void OnDeliveryUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalMoney
        {
            get
            {
                return _TotalMoney;
            }
            set
            {
                OnTotalMoneyChanging(value);
                ReportPropertyChanging("TotalMoney");
                _TotalMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalMoney");
                OnTotalMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalMoney;
        partial void OnTotalMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalMoneyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ChangeMoney
        {
            get
            {
                return _ChangeMoney;
            }
            set
            {
                OnChangeMoneyChanging(value);
                ReportPropertyChanging("ChangeMoney");
                _ChangeMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChangeMoney");
                OnChangeMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _ChangeMoney;
        partial void OnChangeMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnChangeMoneyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ServiceCost
        {
            get
            {
                return _ServiceCost;
            }
            set
            {
                OnServiceCostChanging(value);
                ReportPropertyChanging("ServiceCost");
                _ServiceCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ServiceCost");
                OnServiceCostChanged();
            }
        }
        private Nullable<global::System.Decimal> _ServiceCost;
        partial void OnServiceCostChanging(Nullable<global::System.Decimal> value);
        partial void OnServiceCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ExpressDelivery
        {
            get
            {
                return _ExpressDelivery;
            }
            set
            {
                OnExpressDeliveryChanging(value);
                ReportPropertyChanging("ExpressDelivery");
                _ExpressDelivery = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpressDelivery");
                OnExpressDeliveryChanged();
            }
        }
        private Nullable<global::System.Boolean> _ExpressDelivery;
        partial void OnExpressDeliveryChanging(Nullable<global::System.Boolean> value);
        partial void OnExpressDeliveryChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Location_Order_cangooru_Order", "cangooru_Location_Order")]
        public EntityCollection<cangooru_Location_Order> cangooru_Location_Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cangooru_Location_Order>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Order", "cangooru_Location_Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cangooru_Location_Order>("xvdenovembro1565Model.FK_cangooru_Location_Order_cangooru_Order", "cangooru_Location_Order", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Order_cangooru_OrderStatus", "cangooru_OrderStatus")]
        public cangooru_OrderStatus cangooru_OrderStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_OrderStatus>("xvdenovembro1565Model.FK_cangooru_Order_cangooru_OrderStatus", "cangooru_OrderStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_OrderStatus>("xvdenovembro1565Model.FK_cangooru_Order_cangooru_OrderStatus", "cangooru_OrderStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cangooru_OrderStatus> cangooru_OrderStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_OrderStatus>("xvdenovembro1565Model.FK_cangooru_Order_cangooru_OrderStatus", "cangooru_OrderStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cangooru_OrderStatus>("xvdenovembro1565Model.FK_cangooru_Order_cangooru_OrderStatus", "cangooru_OrderStatus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Purchase_cangooru_Order", "cangooru_Purchase")]
        public EntityCollection<cangooru_Purchase> cangooru_Purchase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cangooru_Purchase>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_Order", "cangooru_Purchase");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cangooru_Purchase>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_Order", "cangooru_Purchase", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xvdenovembro1565Model", Name="cangooru_OrderStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cangooru_OrderStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cangooru_OrderStatus object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static cangooru_OrderStatus Createcangooru_OrderStatus(global::System.Int32 id, global::System.String name, global::System.String description)
        {
            cangooru_OrderStatus cangooru_OrderStatus = new cangooru_OrderStatus();
            cangooru_OrderStatus.Id = id;
            cangooru_OrderStatus.Name = name;
            cangooru_OrderStatus.Description = description;
            return cangooru_OrderStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Order_cangooru_OrderStatus", "cangooru_Order")]
        public EntityCollection<cangooru_Order> cangooru_Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Order_cangooru_OrderStatus", "cangooru_Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Order_cangooru_OrderStatus", "cangooru_Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xvdenovembro1565Model", Name="cangooru_Purchase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cangooru_Purchase : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cangooru_Purchase object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="purchaseStatusID">Initial value of the PurchaseStatusID property.</param>
        /// <param name="purchaseInitiatedDate">Initial value of the PurchaseInitiatedDate property.</param>
        public static cangooru_Purchase Createcangooru_Purchase(global::System.Guid id, global::System.Int32 purchaseStatusID, global::System.DateTime purchaseInitiatedDate)
        {
            cangooru_Purchase cangooru_Purchase = new cangooru_Purchase();
            cangooru_Purchase.Id = id;
            cangooru_Purchase.PurchaseStatusID = purchaseStatusID;
            cangooru_Purchase.PurchaseInitiatedDate = purchaseInitiatedDate;
            return cangooru_Purchase;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PurchaseStatusID
        {
            get
            {
                return _PurchaseStatusID;
            }
            set
            {
                OnPurchaseStatusIDChanging(value);
                ReportPropertyChanging("PurchaseStatusID");
                _PurchaseStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PurchaseStatusID");
                OnPurchaseStatusIDChanged();
            }
        }
        private global::System.Int32 _PurchaseStatusID;
        partial void OnPurchaseStatusIDChanging(global::System.Int32 value);
        partial void OnPurchaseStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PurchaseInitiatedDate
        {
            get
            {
                return _PurchaseInitiatedDate;
            }
            set
            {
                OnPurchaseInitiatedDateChanging(value);
                ReportPropertyChanging("PurchaseInitiatedDate");
                _PurchaseInitiatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PurchaseInitiatedDate");
                OnPurchaseInitiatedDateChanged();
            }
        }
        private global::System.DateTime _PurchaseInitiatedDate;
        partial void OnPurchaseInitiatedDateChanging(global::System.DateTime value);
        partial void OnPurchaseInitiatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private Nullable<global::System.Decimal> _Value;
        partial void OnValueChanging(Nullable<global::System.Decimal> value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private Nullable<global::System.Guid> _OrderId;
        partial void OnOrderIdChanging(Nullable<global::System.Guid> value);
        partial void OnOrderIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Purchase_cangooru_Order", "cangooru_Order")]
        public cangooru_Order cangooru_Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_Order", "cangooru_Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_Order", "cangooru_Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cangooru_Order> cangooru_OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_Order", "cangooru_Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cangooru_Order>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_Order", "cangooru_Order", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Purchase_cangooru_PurchaseStatus", "cangooru_PurchaseStatus")]
        public cangooru_PurchaseStatus cangooru_PurchaseStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_PurchaseStatus>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_PurchaseStatus", "cangooru_PurchaseStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_PurchaseStatus>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_PurchaseStatus", "cangooru_PurchaseStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cangooru_PurchaseStatus> cangooru_PurchaseStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cangooru_PurchaseStatus>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_PurchaseStatus", "cangooru_PurchaseStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cangooru_PurchaseStatus>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_PurchaseStatus", "cangooru_PurchaseStatus", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xvdenovembro1565Model", Name="cangooru_PurchaseStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cangooru_PurchaseStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cangooru_PurchaseStatus object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static cangooru_PurchaseStatus Createcangooru_PurchaseStatus(global::System.Int32 id, global::System.String name, global::System.String description)
        {
            cangooru_PurchaseStatus cangooru_PurchaseStatus = new cangooru_PurchaseStatus();
            cangooru_PurchaseStatus.Id = id;
            cangooru_PurchaseStatus.Name = name;
            cangooru_PurchaseStatus.Description = description;
            return cangooru_PurchaseStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Purchase_cangooru_PurchaseStatus", "cangooru_Purchase")]
        public EntityCollection<cangooru_Purchase> cangooru_Purchase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cangooru_Purchase>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_PurchaseStatus", "cangooru_Purchase");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cangooru_Purchase>("xvdenovembro1565Model.FK_cangooru_Purchase_cangooru_PurchaseStatus", "cangooru_Purchase", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xvdenovembro1565Model", Name="cangooru_Region")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cangooru_Region : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cangooru_Region object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="briefName">Initial value of the BriefName property.</param>
        public static cangooru_Region Createcangooru_Region(global::System.Guid id, global::System.String name, global::System.String briefName)
        {
            cangooru_Region cangooru_Region = new cangooru_Region();
            cangooru_Region.Id = id;
            cangooru_Region.Name = name;
            cangooru_Region.BriefName = briefName;
            return cangooru_Region;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BriefName
        {
            get
            {
                return _BriefName;
            }
            set
            {
                OnBriefNameChanging(value);
                ReportPropertyChanging("BriefName");
                _BriefName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BriefName");
                OnBriefNameChanged();
            }
        }
        private global::System.String _BriefName;
        partial void OnBriefNameChanging(global::System.String value);
        partial void OnBriefNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xvdenovembro1565Model", "FK_cangooru_Location_cangooru_Region", "cangooru_Location")]
        public EntityCollection<cangooru_Location> cangooru_Location
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cangooru_Location>("xvdenovembro1565Model.FK_cangooru_Location_cangooru_Region", "cangooru_Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cangooru_Location>("xvdenovembro1565Model.FK_cangooru_Location_cangooru_Region", "cangooru_Location", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
